#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { marked } from "marked";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const STATUS_COLOURS = {
  "not started": "Grey",
  draft: "Yellow",
  "in progress": "Blue",
  review: "Purple",
  done: "Green",
  blocked: "Red",
};

const PANEL_TYPES = {
  note: "info",
  warning: "warning",
  decision: "note",
  tip: "tip",
};

const DASHBOARD_BODY = `<h1>AIDOS Project Dashboard</h1>
<p>Auto-generated by the AIDOS Confluence Connector. Do not edit manually.</p>
<h2>Epics</h2>
<ac:structured-macro ac:name="detailssummary">
  <ac:parameter ac:name="cql">label = "epic" AND ancestor = currentContent()</ac:parameter>
</ac:structured-macro>
<h2>Features</h2>
<ac:structured-macro ac:name="detailssummary">
  <ac:parameter ac:name="cql">label = "feature" AND ancestor = currentContent()</ac:parameter>
</ac:structured-macro>`;

const STORIES_SECTION = `<h2>Stories</h2>
<ac:structured-macro ac:name="detailssummary">
  <ac:parameter ac:name="cql">label = "story" AND parent = currentContent()</ac:parameter>
</ac:structured-macro>`;

const CHILDREN_MACRO = `\n<ac:structured-macro ac:name="children" />`;

// Bump this to force republish of all pages (e.g. after a connector change
// that alters output but not source content — label changes, macro format, etc.)
const CONNECTOR_VERSION = "1";

const HASH_PROPERTY_KEY = "aidos-content-hash";

function contentHash(body) {
  return createHash("sha256")
    .update(CONNECTOR_VERSION + body)
    .digest("hex")
    .slice(0, 16);
}

// Scale labels: epic (root files), feature (folder pages), story (files inside features)
// Passed explicitly through the recursion — not derived from depth.

// Title template — set from manifest config in main(). %title% is replaced with the raw title.
let titleTemplate = "%title%";

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

let authHeader;

function requireAuth() {
  const email = process.env.CONFLUENCE_EMAIL;
  const token = process.env.CONFLUENCE_TOKEN;
  if (!email || !token) {
    throw new Error(
      "CONFLUENCE_EMAIL and CONFLUENCE_TOKEN environment variables are required",
    );
  }
  authHeader = `Basic ${Buffer.from(`${email}:${token}`).toString("base64")}`;
}

// ---------------------------------------------------------------------------
// Confluence API helpers
// ---------------------------------------------------------------------------

async function confluenceFetch(url, options = {}, label = "") {
  const res = await fetch(url, {
    ...options,
    headers: {
      Authorization: authHeader,
      "Content-Type": "application/json",
      Accept: "application/json",
      ...options.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(
      `Confluence API ${res.status}${label ? ` [${label}]` : ""}: ${body}`,
    );
  }
  return res.json();
}

async function getPage(baseUrl, pageId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/api/v2/pages/${pageId}?body-format=storage`,
    {},
    `getPage ${pageId}`,
  );
  return {
    id: data.id,
    title: data.title,
    version: data.version?.number ?? 1,
    body: data.body?.storage?.value ?? "",
    spaceId: data.spaceId,
  };
}

async function getSpaceKey(baseUrl, spaceId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/api/v2/spaces/${spaceId}`,
  );
  return data.key;
}

async function getChildPages(baseUrl, parentId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/rest/api/content/${parentId}/child/page?limit=250`,
    {},
    `getChildPages ${parentId}`,
  );
  return (data.results ?? []).map((p) => ({ id: p.id, title: p.title }));
}

/** Search for an active page by title, scoped to descendants of rootPageId only. */
async function findPageByTitle(baseUrl, rootPageId, title) {
  const cql = `ancestor=${rootPageId} AND title="${title}" AND type=page`;
  const data = await confluenceFetch(
    `${baseUrl}/wiki/rest/api/content/search?cql=${encodeURIComponent(cql)}&limit=1`,
    {},
    `findPageByTitle "${title}"`,
  );
  const results = data.results ?? [];
  return results.length > 0
    ? { id: results[0].id, title: results[0].title }
    : null;
}

async function createPage(baseUrl, spaceKey, parentId, title, body) {
  return confluenceFetch(
    `${baseUrl}/wiki/rest/api/content`,
    {
      method: "POST",
      body: JSON.stringify({
        type: "page",
        title,
        space: { key: spaceKey },
        ancestors: [{ id: parentId }],
        body: { storage: { value: body, representation: "storage" } },
      }),
    },
    `createPage "${title}"`,
  );
}

async function updatePage(baseUrl, pageId, title, body, version) {
  return confluenceFetch(
    `${baseUrl}/wiki/rest/api/content/${pageId}`,
    {
      method: "PUT",
      body: JSON.stringify({
        type: "page",
        title,
        body: { storage: { value: body, representation: "storage" } },
        version: { number: version + 1 },
      }),
    },
    `updatePage "${title}" (${pageId} v${version}→${version + 1})`,
  );
}

async function addLabels(baseUrl, pageId, labels) {
  return confluenceFetch(
    `${baseUrl}/wiki/rest/api/content/${pageId}/label`,
    {
      method: "POST",
      body: JSON.stringify(labels.map((name) => ({ prefix: "global", name }))),
    },
    `addLabels ${pageId} [${labels.join(", ")}]`,
  );
}

/** Read the stored content hash from a page property. Returns null if not set. */
async function getStoredHash(baseUrl, pageId) {
  try {
    const data = await confluenceFetch(
      `${baseUrl}/wiki/rest/api/content/${pageId}/property/${HASH_PROPERTY_KEY}`,
      {},
      `getHash ${pageId}`,
    );
    return data.value?.hash ?? null;
  } catch {
    return null;
  }
}

/** Write the content hash as a page property. Creates or updates. */
async function setStoredHash(baseUrl, pageId, hash) {
  // Try to read existing property for its version number
  let version = null;
  try {
    const data = await confluenceFetch(
      `${baseUrl}/wiki/rest/api/content/${pageId}/property/${HASH_PROPERTY_KEY}`,
      {},
      `getHash ${pageId}`,
    );
    version = data.version?.number;
  } catch {
    // Property doesn't exist yet
  }

  if (version) {
    // Update existing property
    await confluenceFetch(
      `${baseUrl}/wiki/rest/api/content/${pageId}/property/${HASH_PROPERTY_KEY}`,
      {
        method: "PUT",
        body: JSON.stringify({
          key: HASH_PROPERTY_KEY,
          value: { hash },
          version: { number: version + 1 },
        }),
      },
      `setHash ${pageId}`,
    );
  } else {
    // Create new property
    await confluenceFetch(
      `${baseUrl}/wiki/rest/api/content/${pageId}/property`,
      {
        method: "POST",
        body: JSON.stringify({
          key: HASH_PROPERTY_KEY,
          value: { hash },
        }),
      },
      `setHash ${pageId}`,
    );
  }
}

// ---------------------------------------------------------------------------
// Markdown parsing
// ---------------------------------------------------------------------------

// Supports two metadata formats (bold wins if both are present):
//   1. **Status:** ACCEPTED         — inline bold fields, can appear anywhere
//   2. A leading markdown table right after the H1:
//        | Status | ACCEPTED |
//        | --- | --- |
//        | Owner | Simon |
function parseMetadata(markdown) {
  const meta = {};
  const fields = { status: "Status", owner: "Owner" };

  // Format 1: inline **Key:** Value — takes precedence.
  for (const [key, label] of Object.entries(fields)) {
    const match = markdown.match(
      new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+)`, "i"),
    );
    if (match) meta[key] = match[1].trim();
  }

  // Format 2: leading table, only if a field was not found in bold format.
  if (!meta.status || !meta.owner) {
    const fromTable = parseLeadingMetadataTable(markdown);
    for (const key of Object.keys(fields)) {
      if (!meta[key] && fromTable[key]) meta[key] = fromTable[key];
    }
  }

  return meta;
}

// Extract status/owner from a leading markdown table. Returns {} if the
// document does not start with a table (after optional blank lines and H1).
// Only the first table is considered.
function parseLeadingMetadataTable(markdown) {
  const lines = markdown.split("\n");
  let i = 0;

  // Skip leading blank lines
  while (i < lines.length && lines[i].trim() === "") i++;

  // Optional H1
  if (i < lines.length && lines[i].startsWith("# ")) {
    i++;
    while (i < lines.length && lines[i].trim() === "") i++;
  }

  // Must be followed by a table row
  if (i >= lines.length || !/^\|.*\|\s*$/.test(lines[i])) return {};

  // Consume contiguous table rows
  const rows = [];
  while (i < lines.length && /^\|.*\|\s*$/.test(lines[i])) {
    rows.push(lines[i]);
    i++;
  }

  const meta = {};
  const keyMap = { status: "status", owner: "owner" };
  for (const row of rows) {
    // Skip the separator row (only dashes/colons/pipes/whitespace)
    if (/^\|[\s\-:|]+\|\s*$/.test(row)) continue;

    const cells = row.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length < 2) continue;

    const key = cells[0].toLowerCase();
    const value = cells[1];
    if (keyMap[key] && !meta[key]) meta[key] = value;
  }

  return meta;
}

function deriveLabels(name, scale) {
  const labels = [name.replace(/\.md$/i, ""), "aidos"];
  if (scale) labels.push(scale);
  return labels;
}

// ---------------------------------------------------------------------------
// Content builders
// ---------------------------------------------------------------------------

function titleFromName(name) {
  const raw = name
    .replace(/\.md$/i, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
  return titleTemplate.replace("%title%", raw);
}

function statusColour(status) {
  return STATUS_COLOURS[status.toLowerCase()] ?? "Grey";
}

function statusMacro(status) {
  return `<ac:structured-macro ac:name="status">
  <ac:parameter ac:name="title">${status}</ac:parameter>
  <ac:parameter ac:name="colour">${statusColour(status)}</ac:parameter>
</ac:structured-macro>`;
}

function pagePropertiesMacro(meta) {
  const rows = [];
  if (meta.status) {
    rows.push(
      `      <tr><th>Status</th><td>${statusMacro(meta.status)}</td></tr>`,
    );
  }
  if (meta.owner) {
    rows.push(`      <tr><th>Owner</th><td>${meta.owner}</td></tr>`);
  }
  if (rows.length === 0) return "";
  return `<ac:structured-macro ac:name="details">
  <ac:rich-text-body>
    <table>
${rows.join("\n")}
    </table>
  </ac:rich-text-body>
</ac:structured-macro>`;
}

// ---------------------------------------------------------------------------
// HTML transforms
// ---------------------------------------------------------------------------

function rewriteLinks(html) {
  return html.replace(
    /<a\s+href="([^"]+\.md)">(.*?)<\/a>/gi,
    (_, href, text) => {
      const filename = href.split("/").pop();
      const title = titleFromName(filename);
      return `<ac:link><ri:page ri:content-title="${title}" /><ac:plain-text-link-body><![CDATA[${text}]]></ac:plain-text-link-body></ac:link>`;
    },
  );
}

function rewritePanels(html) {
  return html.replace(
    /<blockquote>\s*<p><strong>(Note|Warning|Decision|Tip):<\/strong>\s*([\s\S]*?)<\/blockquote>/gi,
    (_, label, rest) => {
      const macroName = PANEL_TYPES[label.toLowerCase()] ?? "info";
      return `<ac:structured-macro ac:name="${macroName}">
  <ac:parameter ac:name="title">${label}</ac:parameter>
  <ac:rich-text-body><p>${rest}</ac:rich-text-body>
</ac:structured-macro>`;
    },
  );
}

function rewriteExpand(html) {
  return html.replace(
    /<details>\s*<summary>(.*?)<\/summary>([\s\S]*?)<\/details>/gi,
    (_, title, content) => {
      return `<ac:structured-macro ac:name="expand">
  <ac:parameter ac:name="title">${title.trim()}</ac:parameter>
  <ac:rich-text-body>${content.trim()}</ac:rich-text-body>
</ac:structured-macro>`;
    },
  );
}

// ---------------------------------------------------------------------------
// Marked configuration — code blocks → Confluence code macro
// ---------------------------------------------------------------------------

marked.use({
  renderer: {
    code({ text, lang }) {
      const langParam = lang
        ? `\n  <ac:parameter ac:name="language">${lang}</ac:parameter>`
        : "";
      return `<ac:structured-macro ac:name="code">${langParam}
  <ac:plain-text-body><![CDATA[${text}]]></ac:plain-text-body>
</ac:structured-macro>\n`;
    },
  },
});

// ---------------------------------------------------------------------------
// Page body assembly
// ---------------------------------------------------------------------------

/**
 * Strip the header block that the connector already surfaces in Page Properties.
 * Handles both supported metadata formats: **Key:** Value lines and a leading
 * markdown table.
 */
function stripHeader(markdown) {
  const lines = markdown.split("\n");
  let i = 0;

  // Skip leading blank lines
  while (i < lines.length && lines[i].trim() === "") i++;

  // Skip the first H1 heading
  if (i < lines.length && lines[i].startsWith("# ")) i++;

  // Skip blank lines, **Key:** Value metadata lines, and a leading metadata table
  while (i < lines.length) {
    const line = lines[i].trim();
    if (line === "") { i++; continue; }
    if (/^\*\*\w[\w\s]*:\*\*/.test(line)) { i++; continue; }
    // Leading metadata table: consume contiguous `|...|` rows (header, separator, data)
    if (/^\|.*\|\s*$/.test(line)) {
      while (i < lines.length && /^\|.*\|\s*$/.test(lines[i])) i++;
      continue;
    }
    break;
  }

  return lines.slice(i).join("\n");
}

function convertMarkdown(markdown) {
  let html = marked.parse(stripHeader(markdown));
  html = rewriteLinks(html);
  html = rewritePanels(html);
  html = rewriteExpand(html);
  return html;
}

function buildPageBody(markdown, meta) {
  const html = convertMarkdown(markdown);
  const props = pagePropertiesMacro(meta);
  return props ? `${props}\n${html}` : html;
}

/** Build a feature page: properties → Stories section → content. */
function buildFeaturePageBody(markdown, meta) {
  const html = convertMarkdown(markdown);
  const props = pagePropertiesMacro(meta);
  const parts = [];
  if (props) parts.push(props);
  parts.push(STORIES_SECTION);
  parts.push(html);
  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Publish a single page — create or update, apply labels, return page ID
// ---------------------------------------------------------------------------

async function publishPage(ctx, parentId, childPages, title, body, labels) {
  const { baseUrl, spaceKey, dryRun } = ctx;
  const hash = contentHash(body);

  if (dryRun) {
    const existing = childPages.get(title);
    return existing ?? `dry-run-${title}`;
  }

  // Check children of parent first, then search descendants of root as fallback
  let pageId = childPages.get(title);
  if (!pageId) {
    const found = await findPageByTitle(baseUrl, ctx.rootPageId, title);
    if (found) pageId = found.id;
  }

  if (pageId) {
    // Check if content has changed via stored hash
    const storedHash = await getStoredHash(baseUrl, pageId);
    if (storedHash === hash) {
      console.log("  Unchanged: %s (page %s)", title, pageId);
      ctx.stats.unchanged++;
      return pageId;
    }

    const page = await getPage(baseUrl, pageId);
    await updatePage(baseUrl, pageId, title, body, page.version);
    await addLabels(baseUrl, pageId, labels);
    await setStoredHash(baseUrl, pageId, hash);
    console.log("  Updated: %s (page %s, v%d → v%d)", title, pageId, page.version, page.version + 1);
    ctx.stats.updated++;
    return pageId;
  }

  // Two-step create: minimal body first (avoids Fabric editor macro
  // restrictions), then immediately update with full storage format.
  const created = await createPage(baseUrl, spaceKey, parentId, title, "<p></p>");
  await updatePage(baseUrl, created.id, title, body, 1);
  await addLabels(baseUrl, created.id, labels);
  await setStoredHash(baseUrl, created.id, hash);
  console.log("  Created: %s (page %s)", title, created.id);
  ctx.stats.created++;
  return created.id;
}

// ---------------------------------------------------------------------------
// Recursive directory publisher
// ---------------------------------------------------------------------------

async function publishDirectory(ctx, parentId, dirPath, depth, skipFile, fileScale) {
  const { baseUrl, dryRun } = ctx;
  const indent = "  ".repeat(depth);

  // Look up existing child pages of this parent
  let childPages = new Map();
  if (!dryRun) {
    const children = await getChildPages(baseUrl, parentId);
    childPages = new Map(children.map((c) => [c.title, c.id]));
  }

  // Read directory entries
  const entries = await readdir(dirPath, { withFileTypes: true });
  const mdFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith(".md") && e.name !== skipFile)
    .map((e) => e.name)
    .sort();
  const subdirs = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  // Publish .md files as child pages (excluding body file already used by parent)
  for (const filename of mdFiles) {
    const markdown = await readFile(join(dirPath, filename), "utf-8");
    const meta = parseMetadata(markdown);
    const labels = deriveLabels(filename, fileScale);
    const title = titleFromName(filename);
    const body = buildPageBody(markdown, meta);

    if (dryRun) {
      const action = childPages.has(title) ? "update" : "create";
      console.log("%s[page] %s — %s", indent, title, action);
      if (Object.keys(meta).length)
        console.log("%s       Properties: %o", indent, meta);
      console.log("%s       Labels: %s", indent, labels.join(", "));
    }

    await publishPage(ctx, parentId, childPages, title, body, labels);
  }

  // Process subdirectories
  const SCALE_FOLDERS = new Set(["epic", "feature", "story"]);

  for (const subdir of subdirs) {
    const subdirPath = join(dirPath, subdir);

    // Scale-named folders (epic/, feature/, story/) are transparent groupings.
    // Contents promoted to parent level with the folder name as scale label.
    if (SCALE_FOLDERS.has(subdir)) {
      if (dryRun) {
        console.log("%s[%s/] promoting contents to parent", indent, subdir);
      }
      await publishDirectory(ctx, parentId, subdirPath, depth, null, subdir);
      continue;
    }

    const title = titleFromName(subdir);

    // Check for a matching .md body file INSIDE the subdirectory
    const bodyFileName = `${subdir}.md`;
    const subdirEntries = await readdir(subdirPath);
    const hasBody = subdirEntries.includes(bodyFileName);

    // Folders with body files under epic scale are features
    const isFeature = fileScale === "epic" && hasBody;

    let body;
    let labels;
    let meta = {};
    let childScale = null;

    if (hasBody) {
      const markdown = await readFile(join(subdirPath, bodyFileName), "utf-8");
      meta = parseMetadata(markdown);
      if (isFeature) {
        labels = deriveLabels(bodyFileName, "feature");
        body = buildFeaturePageBody(markdown, meta) + CHILDREN_MACRO;
        childScale = "story";
      } else {
        labels = deriveLabels(bodyFileName, fileScale);
        body = buildPageBody(markdown, meta) + CHILDREN_MACRO;
        childScale = fileScale;
      }
    } else {
      // No matching .md — auto-generated page with Children Display macro
      labels = [subdir, "aidos"];
      body = `<h1>${title}</h1>${CHILDREN_MACRO}`;
    }

    if (dryRun) {
      const action = childPages.has(title) ? "update" : "create";
      const source = hasBody
        ? `from ${subdir}/${bodyFileName}`
        : "auto-generated";
      console.log(
        "%s[folder] %s — %s (%s)",
        indent,
        title,
        action,
        source,
      );
      if (Object.keys(meta).length)
        console.log("%s         Properties: %o", indent, meta);
      console.log("%s         Labels: %s", indent, labels.join(", "));
    }

    const pageId = await publishPage(
      ctx,
      parentId,
      childPages,
      title,
      body,
      labels,
    );

    // Recurse into the subdirectory
    await publishDirectory(
      ctx,
      pageId,
      subdirPath,
      depth + 1,
      hasBody ? bodyFileName : null,
      childScale,
    );
  }
}

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------

async function ensureDashboard(ctx) {
  const { baseUrl, rootPageId, dryRun } = ctx;

  if (dryRun) {
    console.log("[dry-run] Would check/set dashboard on root page %s\n", rootPageId);
    return "UNKNOWN";
  }

  let page = await getPage(baseUrl, rootPageId);
  const spaceKey = await getSpaceKey(baseUrl, page.spaceId);

  if (page.body.includes("detailssummary")) {
    console.log("Root page already has dashboard macro — skipping");
    return spaceKey;
  }

  console.log("Setting dashboard body on root page %s", rootPageId);
  try {
    await updatePage(baseUrl, rootPageId, page.title, DASHBOARD_BODY, page.version);
  } catch (err) {
    // Version conflict — re-fetch and retry once
    console.log("Dashboard update failed (%s), retrying...", err.message.slice(0, 80));
    page = await getPage(baseUrl, rootPageId);
    await updatePage(baseUrl, rootPageId, page.title, DASHBOARD_BODY, page.version);
  }

  return spaceKey;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const manifestPath = args.find((a) => !a.startsWith("--"));

  if (!manifestPath) {
    console.error("Usage: publish.js <manifest-path> [--dry-run]");
    process.exit(1);
  }

  const resolvedPath = resolve(manifestPath);
  const aidosDir = dirname(resolvedPath);
  const manifest = JSON.parse(await readFile(resolvedPath, "utf-8"));

  const config = manifest.publish?.confluence;
  if (!config) {
    throw new Error("No publish.confluence config found in manifest");
  }

  const { baseUrl, rootPageId } = config;
  if (!baseUrl || !rootPageId) {
    throw new Error("publish.confluence must include baseUrl and rootPageId");
  }

  if (config.titleTemplate) {
    if (!config.titleTemplate.includes("%title%")) {
      throw new Error("titleTemplate must contain %title% placeholder");
    }
    titleTemplate = config.titleTemplate;
  }

  if (!dryRun) {
    requireAuth();
  }

  console.log(
    "Publishing to %s (root: %s)%s\n",
    baseUrl,
    rootPageId,
    dryRun ? " [DRY RUN]" : "",
  );

  const ctx = {
    baseUrl,
    spaceKey: null,
    rootPageId,
    dryRun,
    stats: { created: 0, updated: 0, unchanged: 0 },
  };

  // Ensure dashboard and derive space key
  ctx.spaceKey = await ensureDashboard(ctx);

  // Recursively publish the .aidos/ directory tree
  await publishDirectory(ctx, rootPageId, aidosDir, 0, null, "epic");

  console.log(
    "\nDone — created: %d, updated: %d, unchanged: %d",
    ctx.stats.created,
    ctx.stats.updated,
    ctx.stats.unchanged,
  );
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
