#!/usr/bin/env node

import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { marked } from "marked";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const STATUS_COLOURS = {
  "Not Started": "Grey",
  Draft: "Yellow",
  "In Progress": "Blue",
  Review: "Purple",
  Done: "Green",
  Blocked: "Red",
};

const DASHBOARD_BODY = `<h1>AIDOS Project Dashboard</h1>
<p>Auto-generated by the AIDOS Confluence Connector. Do not edit manually.</p>
<ac:structured-macro ac:name="detailssummary">
  <ac:parameter ac:name="cql">parent = "currentContent()"</ac:parameter>
</ac:structured-macro>`;

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

let authHeader;

function requireAuth() {
  const email = process.env.CONFLUENCE_EMAIL;
  const token = process.env.CONFLUENCE_TOKEN;
  if (!email || !token) {
    throw new Error(
      "CONFLUENCE_EMAIL and CONFLUENCE_TOKEN environment variables are required",
    );
  }
  authHeader = `Basic ${Buffer.from(`${email}:${token}`).toString("base64")}`;
}

// ---------------------------------------------------------------------------
// Confluence API helpers
// ---------------------------------------------------------------------------

async function confluenceFetch(url, options = {}) {
  const res = await fetch(url, {
    ...options,
    headers: {
      Authorization: authHeader,
      "Content-Type": "application/json",
      Accept: "application/json",
      ...options.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Confluence API ${res.status}: ${body}`);
  }
  return res.json();
}

/** GET a single page (v2) — returns id, title, version number, and storage body. */
async function getPage(baseUrl, pageId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/api/v2/pages/${pageId}?body-format=storage`,
  );
  return {
    id: data.id,
    title: data.title,
    version: data.version?.number ?? 1,
    body: data.body?.storage?.value ?? "",
  };
}

/** GET child pages of a parent (v1) — returns array of { id, title }. */
async function getChildPages(baseUrl, parentId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/rest/api/content/${parentId}/child/page?limit=250`,
  );
  return (data.results ?? []).map((p) => ({ id: p.id, title: p.title }));
}

/** POST — create a new page as a child of parentId (v1, storage format). */
async function createPage(baseUrl, spaceKey, parentId, title, body) {
  return confluenceFetch(`${baseUrl}/wiki/rest/api/content`, {
    method: "POST",
    body: JSON.stringify({
      type: "page",
      title,
      space: { key: spaceKey },
      ancestors: [{ id: parentId }],
      body: { storage: { value: body, representation: "storage" } },
    }),
  });
}

/** PUT — update an existing page (v1, storage format). Version must be bumped. */
async function updatePage(baseUrl, pageId, title, body, version) {
  return confluenceFetch(`${baseUrl}/wiki/rest/api/content/${pageId}`, {
    method: "PUT",
    body: JSON.stringify({
      type: "page",
      title,
      body: { storage: { value: body, representation: "storage" } },
      version: { number: version + 1 },
    }),
  });
}

// ---------------------------------------------------------------------------
// Content builders
// ---------------------------------------------------------------------------

function statusMacro(status) {
  const colour = STATUS_COLOURS[status] ?? "Grey";
  return `<ac:structured-macro ac:name="status">
  <ac:parameter ac:name="title">${status}</ac:parameter>
  <ac:parameter ac:name="colour">${colour}</ac:parameter>
</ac:structured-macro>`;
}

function pagePropertiesMacro(status) {
  return `<ac:structured-macro ac:name="details">
  <ac:rich-text-body>
    <table>
      <tr>
        <th>Status</th>
        <td>${statusMacro(status)}</td>
      </tr>
    </table>
  </ac:rich-text-body>
</ac:structured-macro>`;
}

function buildPageBody(markdown, status) {
  const html = marked.parse(markdown);
  return `${pagePropertiesMacro(status)}\n${html}`;
}

function titleFromFilename(filename) {
  return filename
    .replace(/\.md$/i, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// ---------------------------------------------------------------------------
// Core logic
// ---------------------------------------------------------------------------

async function ensureDashboard(baseUrl, rootPageId, dryRun) {
  if (dryRun) {
    console.log("[dry-run] Would check/set dashboard on root page %s", rootPageId);
    console.log("[dry-run] Dashboard body:\n%s\n", DASHBOARD_BODY);
    return;
  }

  const page = await getPage(baseUrl, rootPageId);
  if (page.body.includes("detailssummary")) {
    console.log("Root page already has dashboard macro — skipping");
    return;
  }

  console.log("Setting dashboard body on root page %s", rootPageId);
  await updatePage(baseUrl, rootPageId, page.title, DASHBOARD_BODY, page.version);
}

async function publishArtifact(
  baseUrl,
  spaceKey,
  rootPageId,
  childPages,
  aidosDir,
  filename,
  status,
  dryRun,
) {
  const title = titleFromFilename(filename);
  const filePath = join(aidosDir, filename);
  const markdown = await readFile(filePath, "utf-8");
  const body = buildPageBody(markdown, status);

  if (dryRun) {
    const colour = STATUS_COLOURS[status] ?? "Grey";
    const existing = childPages.get(title);
    const action = existing ? `update (page ${existing})` : "create";
    console.log("\n--- %s [%s → %s] — %s ---", title, status, colour, action);
    console.log(body);
    return existing ? "updated" : "created";
  }

  const existing = childPages.get(title);
  if (existing) {
    const page = await getPage(baseUrl, existing);
    await updatePage(baseUrl, existing, title, body, page.version);
    console.log("Updated: %s (page %s, version %d → %d)", title, existing, page.version, page.version + 1);
    return "updated";
  }

  const created = await createPage(baseUrl, spaceKey, rootPageId, title, body);
  console.log("Created: %s (page %s)", title, created.id);
  return "created";
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const manifestPath = args.find((a) => !a.startsWith("--"));

  if (!manifestPath) {
    console.error("Usage: publish.js <manifest-path> [--dry-run]");
    process.exit(1);
  }

  const resolvedPath = resolve(manifestPath);
  const aidosDir = dirname(resolvedPath);
  const manifest = JSON.parse(await readFile(resolvedPath, "utf-8"));

  const { confluenceBaseUrl: baseUrl, spaceKey, rootPageId } = manifest.publish;
  if (!baseUrl || !spaceKey || !rootPageId) {
    throw new Error("manifest.publish must include confluenceBaseUrl, spaceKey, and rootPageId");
  }

  if (!dryRun) {
    requireAuth();
  }

  console.log("Publishing to %s (space: %s, root: %s)%s", baseUrl, spaceKey, rootPageId, dryRun ? " [DRY RUN]" : "");

  // Ensure the root page has the dashboard macro
  await ensureDashboard(baseUrl, rootPageId, dryRun);

  // Build title→id map of existing child pages
  let childPages = new Map();
  if (!dryRun) {
    const children = await getChildPages(baseUrl, rootPageId);
    childPages = new Map(children.map((c) => [c.title, c.id]));
    console.log("Found %d existing child pages", childPages.size);
  }

  // Publish each artifact
  let created = 0;
  let updated = 0;

  for (const [filename, meta] of Object.entries(manifest.artifacts)) {
    const result = await publishArtifact(
      baseUrl,
      spaceKey,
      rootPageId,
      childPages,
      aidosDir,
      filename,
      meta.status,
      dryRun,
    );
    if (result === "created") created++;
    if (result === "updated") updated++;
  }

  console.log("\nDone — created: %d, updated: %d", created, updated);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
