#!/usr/bin/env node

import { readFile, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { marked } from "marked";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const STATUS_COLOURS = {
  "not started": "Grey",
  draft: "Yellow",
  "in progress": "Blue",
  review: "Purple",
  done: "Green",
  blocked: "Red",
};

const PANEL_TYPES = {
  note: "info",
  warning: "warning",
  decision: "note",
  tip: "tip",
};

const DASHBOARD_BODY = `<h1>AIDOS Project Dashboard</h1>
<p>Auto-generated by the AIDOS Confluence Connector. Do not edit manually.</p>
<ac:structured-macro ac:name="detailssummary">
  <ac:parameter ac:name="cql">parent = "currentContent()"</ac:parameter>
</ac:structured-macro>`;

const CHILDREN_MACRO = `\n<ac:structured-macro ac:name="children">
  <ac:parameter ac:name="all">true</ac:parameter>
</ac:structured-macro>`;

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

let authHeader;

function requireAuth() {
  const email = process.env.CONFLUENCE_EMAIL;
  const token = process.env.CONFLUENCE_TOKEN;
  if (!email || !token) {
    throw new Error(
      "CONFLUENCE_EMAIL and CONFLUENCE_TOKEN environment variables are required",
    );
  }
  authHeader = `Basic ${Buffer.from(`${email}:${token}`).toString("base64")}`;
}

// ---------------------------------------------------------------------------
// Confluence API helpers
// ---------------------------------------------------------------------------

async function confluenceFetch(url, options = {}) {
  const res = await fetch(url, {
    ...options,
    headers: {
      Authorization: authHeader,
      "Content-Type": "application/json",
      Accept: "application/json",
      ...options.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Confluence API ${res.status}: ${body}`);
  }
  return res.json();
}

async function getPage(baseUrl, pageId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/api/v2/pages/${pageId}?body-format=storage`,
  );
  return {
    id: data.id,
    title: data.title,
    version: data.version?.number ?? 1,
    body: data.body?.storage?.value ?? "",
    spaceId: data.spaceId,
  };
}

async function getSpaceKey(baseUrl, spaceId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/api/v2/spaces/${spaceId}`,
  );
  return data.key;
}

async function getChildPages(baseUrl, parentId) {
  const data = await confluenceFetch(
    `${baseUrl}/wiki/rest/api/content/${parentId}/child/page?limit=250`,
  );
  return (data.results ?? []).map((p) => ({ id: p.id, title: p.title }));
}

async function createPage(baseUrl, spaceKey, parentId, title, body) {
  return confluenceFetch(`${baseUrl}/wiki/rest/api/content`, {
    method: "POST",
    body: JSON.stringify({
      type: "page",
      title,
      space: { key: spaceKey },
      ancestors: [{ id: parentId }],
      body: { storage: { value: body, representation: "storage" } },
    }),
  });
}

async function updatePage(baseUrl, pageId, title, body, version) {
  return confluenceFetch(`${baseUrl}/wiki/rest/api/content/${pageId}`, {
    method: "PUT",
    body: JSON.stringify({
      type: "page",
      title,
      body: { storage: { value: body, representation: "storage" } },
      version: { number: version + 1 },
    }),
  });
}

async function addLabels(baseUrl, pageId, labels) {
  return confluenceFetch(
    `${baseUrl}/wiki/rest/api/content/${pageId}/label`,
    {
      method: "POST",
      body: JSON.stringify(labels.map((name) => ({ prefix: "global", name }))),
    },
  );
}

// ---------------------------------------------------------------------------
// Markdown parsing
// ---------------------------------------------------------------------------

function parseMetadata(markdown) {
  const meta = {};
  const fields = { status: "Status", scale: "Scale", owner: "Owner" };
  for (const [key, label] of Object.entries(fields)) {
    const match = markdown.match(
      new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+)`, "i"),
    );
    if (match) meta[key] = match[1].trim();
  }
  return meta;
}

function deriveLabels(name, meta) {
  const labels = [name.replace(/\.md$/i, ""), "aidos"];
  if (meta.scale) labels.push(meta.scale.toLowerCase());
  return labels;
}

// ---------------------------------------------------------------------------
// Content builders
// ---------------------------------------------------------------------------

function titleFromName(name) {
  return name
    .replace(/\.md$/i, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function statusColour(status) {
  return STATUS_COLOURS[status.toLowerCase()] ?? "Grey";
}

function statusMacro(status) {
  return `<ac:structured-macro ac:name="status">
  <ac:parameter ac:name="title">${status}</ac:parameter>
  <ac:parameter ac:name="colour">${statusColour(status)}</ac:parameter>
</ac:structured-macro>`;
}

function pagePropertiesMacro(meta) {
  const rows = [];
  if (meta.status) {
    rows.push(
      `      <tr><th>Status</th><td>${statusMacro(meta.status)}</td></tr>`,
    );
  }
  if (meta.scale) {
    rows.push(`      <tr><th>Scale</th><td>${meta.scale}</td></tr>`);
  }
  if (meta.owner) {
    rows.push(`      <tr><th>Owner</th><td>${meta.owner}</td></tr>`);
  }
  if (rows.length === 0) return "";
  return `<ac:structured-macro ac:name="details">
  <ac:rich-text-body>
    <table>
${rows.join("\n")}
    </table>
  </ac:rich-text-body>
</ac:structured-macro>`;
}

// ---------------------------------------------------------------------------
// HTML transforms
// ---------------------------------------------------------------------------

function rewriteLinks(html) {
  return html.replace(
    /<a\s+href="([^"]+\.md)">(.*?)<\/a>/gi,
    (_, href, text) => {
      const filename = href.split("/").pop();
      const title = titleFromName(filename);
      return `<ac:link><ri:page ri:content-title="${title}" /><ac:plain-text-link-body><![CDATA[${text}]]></ac:plain-text-link-body></ac:link>`;
    },
  );
}

function rewritePanels(html) {
  return html.replace(
    /<blockquote>\s*<p><strong>(Note|Warning|Decision|Tip):<\/strong>\s*([\s\S]*?)<\/blockquote>/gi,
    (_, label, rest) => {
      const macroName = PANEL_TYPES[label.toLowerCase()] ?? "info";
      return `<ac:structured-macro ac:name="${macroName}">
  <ac:parameter ac:name="title">${label}</ac:parameter>
  <ac:rich-text-body><p>${rest}</ac:rich-text-body>
</ac:structured-macro>`;
    },
  );
}

function rewriteExpand(html) {
  return html.replace(
    /<details>\s*<summary>(.*?)<\/summary>([\s\S]*?)<\/details>/gi,
    (_, title, content) => {
      return `<ac:structured-macro ac:name="expand">
  <ac:parameter ac:name="title">${title.trim()}</ac:parameter>
  <ac:rich-text-body>${content.trim()}</ac:rich-text-body>
</ac:structured-macro>`;
    },
  );
}

// ---------------------------------------------------------------------------
// Marked configuration — code blocks → Confluence code macro
// ---------------------------------------------------------------------------

marked.use({
  renderer: {
    code({ text, lang }) {
      const langParam = lang
        ? `\n  <ac:parameter ac:name="language">${lang}</ac:parameter>`
        : "";
      return `<ac:structured-macro ac:name="code">${langParam}
  <ac:plain-text-body><![CDATA[${text}]]></ac:plain-text-body>
</ac:structured-macro>\n`;
    },
  },
});

// ---------------------------------------------------------------------------
// Page body assembly
// ---------------------------------------------------------------------------

function buildPageBody(markdown, meta) {
  let html = marked.parse(markdown);
  html = rewriteLinks(html);
  html = rewritePanels(html);
  html = rewriteExpand(html);
  const props = pagePropertiesMacro(meta);
  return props ? `${props}\n${html}` : html;
}

// ---------------------------------------------------------------------------
// Publish a single page — create or update, apply labels, return page ID
// ---------------------------------------------------------------------------

async function publishPage(ctx, parentId, childPages, title, body, labels) {
  const { baseUrl, spaceKey, dryRun } = ctx;

  if (dryRun) {
    const existing = childPages.get(title);
    return existing ?? `dry-run-${title}`;
  }

  const existing = childPages.get(title);
  if (existing) {
    const page = await getPage(baseUrl, existing);
    await updatePage(baseUrl, existing, title, body, page.version);
    await addLabels(baseUrl, existing, labels);
    ctx.stats.updated++;
    return existing;
  }

  const created = await createPage(baseUrl, spaceKey, parentId, title, body);
  await addLabels(baseUrl, created.id, labels);
  ctx.stats.created++;
  return created.id;
}

// ---------------------------------------------------------------------------
// Recursive directory publisher
// ---------------------------------------------------------------------------

async function publishDirectory(ctx, parentId, dirPath, depth, skipFile) {
  const { baseUrl, dryRun } = ctx;
  const indent = "  ".repeat(depth);

  // Look up existing child pages of this parent
  let childPages = new Map();
  if (!dryRun) {
    const children = await getChildPages(baseUrl, parentId);
    childPages = new Map(children.map((c) => [c.title, c.id]));
  }

  // Read directory entries
  const entries = await readdir(dirPath, { withFileTypes: true });
  const mdFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith(".md") && e.name !== skipFile)
    .map((e) => e.name)
    .sort();
  const subdirs = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  // Publish .md files as child pages (excluding body file already used by parent)
  for (const filename of mdFiles) {
    const markdown = await readFile(join(dirPath, filename), "utf-8");
    const meta = parseMetadata(markdown);
    const labels = deriveLabels(filename, meta);
    const title = titleFromName(filename);
    const body = buildPageBody(markdown, meta);

    if (dryRun) {
      const action = childPages.has(title) ? "update" : "create";
      console.log("%s[page] %s — %s", indent, title, action);
      if (Object.keys(meta).length)
        console.log("%s       Properties: %o", indent, meta);
      console.log("%s       Labels: %s", indent, labels.join(", "));
    }

    await publishPage(ctx, parentId, childPages, title, body, labels);
  }

  // Process subdirectories — each becomes a parent page
  for (const subdir of subdirs) {
    const title = titleFromName(subdir);
    const subdirPath = join(dirPath, subdir);

    // Check for a matching .md body file INSIDE the subdirectory
    const bodyFileName = `${subdir}.md`;
    const subdirEntries = await readdir(subdirPath);
    const hasBody = subdirEntries.includes(bodyFileName);

    let body;
    let labels;
    let meta = {};

    if (hasBody) {
      // Folder has a matching .md file inside — use its content as the page body
      const markdown = await readFile(join(subdirPath, bodyFileName), "utf-8");
      meta = parseMetadata(markdown);
      labels = deriveLabels(bodyFileName, meta);
      body = buildPageBody(markdown, meta) + CHILDREN_MACRO;
    } else {
      // No matching .md inside — auto-generate a page with Children Display macro
      labels = [subdir, "aidos"];
      body = `<h1>${title}</h1>${CHILDREN_MACRO}`;
    }

    if (dryRun) {
      const action = childPages.has(title) ? "update" : "create";
      const source = hasBody ? `from ${subdir}/${bodyFileName}` : "auto-generated";
      console.log("%s[folder] %s — %s (%s)", indent, title, action, source);
      if (Object.keys(meta).length)
        console.log("%s         Properties: %o", indent, meta);
      console.log("%s         Labels: %s", indent, labels.join(", "));
    }

    const pageId = await publishPage(
      ctx,
      parentId,
      childPages,
      title,
      body,
      labels,
    );

    // Recurse into the subdirectory, excluding the body file from child pages
    await publishDirectory(
      ctx,
      pageId,
      subdirPath,
      depth + 1,
      hasBody ? bodyFileName : null,
    );
  }
}

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------

async function ensureDashboard(ctx) {
  const { baseUrl, rootPageId, dryRun } = ctx;

  if (dryRun) {
    console.log("[dry-run] Would check/set dashboard on root page %s\n", rootPageId);
    return "UNKNOWN";
  }

  const page = await getPage(baseUrl, rootPageId);
  const spaceKey = await getSpaceKey(baseUrl, page.spaceId);

  if (page.body.includes("detailssummary")) {
    console.log("Root page already has dashboard macro — skipping");
  } else {
    console.log("Setting dashboard body on root page %s", rootPageId);
    await updatePage(
      baseUrl,
      rootPageId,
      page.title,
      DASHBOARD_BODY,
      page.version,
    );
  }

  return spaceKey;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const manifestPath = args.find((a) => !a.startsWith("--"));

  if (!manifestPath) {
    console.error("Usage: publish.js <manifest-path> [--dry-run]");
    process.exit(1);
  }

  const resolvedPath = resolve(manifestPath);
  const aidosDir = dirname(resolvedPath);
  const manifest = JSON.parse(await readFile(resolvedPath, "utf-8"));

  const config = manifest.publish?.confluence;
  if (!config) {
    throw new Error("No publish.confluence config found in manifest");
  }

  const { baseUrl, rootPageId } = config;
  if (!baseUrl || !rootPageId) {
    throw new Error("publish.confluence must include baseUrl and rootPageId");
  }

  if (!dryRun) {
    requireAuth();
  }

  console.log(
    "Publishing to %s (root: %s)%s\n",
    baseUrl,
    rootPageId,
    dryRun ? " [DRY RUN]" : "",
  );

  const ctx = {
    baseUrl,
    spaceKey: null,
    rootPageId,
    dryRun,
    stats: { created: 0, updated: 0 },
  };

  // Ensure dashboard and derive space key
  ctx.spaceKey = await ensureDashboard(ctx);

  // Recursively publish the .aidos/ directory tree
  await publishDirectory(ctx, rootPageId, aidosDir, 0);

  console.log(
    "\nDone — created: %d, updated: %d",
    ctx.stats.created,
    ctx.stats.updated,
  );
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
